### ISSUE TITLE
Unable to build on Linux with X11

### ISSUE THREAD

**Issue by andrewbrey** [hugoattal/milky-warp#4]
Hi there, thanks for the project! I wanted to give this a shot on Linux (Pop_OS! 22.04, Gnome 42) and running `tauri build` resulted in a compilation error on a missing crate:

![image](https://github.com/hugoattal/milky-warp/assets/34140052/9d63caab-f888-41e1-96cd-b92b009987ce)

For added context, my machine is already fully set up for Tauri development using Tauri's latest instructions and I have been tinkering on Tauri app development locally with no issue for a number of different projects outside of this one.

Do you have any suggestions for how to resolve this build error? Cheers!

**Comment by hugoattal** [comment]
Sorry for the delay, just went back from vacations...

Oh! I think I just forgot to add the x11 crate in the cargo.toml file 🤔.

I'll fix this tomorrow!
